"""Initial migration

Revision ID: d0672b1e1bcf
Revises: 
Create Date: 2024-06-21 12:49:18.590486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0672b1e1bcf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'Users',
        sa.Column('user_id', sa.Integer, primary_key=True, autoincrement=True),
        sa.Column('username', sa.String, nullable=False, unique=True),
        sa.Column('password', sa.String, nullable=False),
        sa.Column('email', sa.String, nullable=False, unique=True),
        sa.Column('balance', sa.Float, default=0.0),
        sa.Column('is_admin', sa.Integer, default=0)
    )
    op.create_table(
        'Items',
        sa.Column('item_id', sa.Integer, primary_key=True, autoincrement=True),
        sa.Column('name', sa.String, nullable=False),
        sa.Column('description', sa.String),
        sa.Column('price', sa.Float, nullable=False),
        sa.Column('stock', sa.Integer, nullable=False)
    )
    op.create_table(
        'Cart',
        sa.Column('cart_id', sa.Integer, primary_key=True, autoincrement=True),
        sa.Column('user_id', sa.Integer, sa.ForeignKey('Users.user_id'), nullable=False),
        sa.Column('item_id', sa.Integer, sa.ForeignKey('Items.item_id'), nullable=False),
        sa.Column('quantity', sa.Integer, nullable=False)
    )
    op.create_table(
        'Orders',
        sa.Column('order_id', sa.Integer, primary_key=True, autoincrement=True),
        sa.Column('user_id', sa.Integer, sa.ForeignKey('Users.user_id'), nullable=False),
        sa.Column('total', sa.Float, nullable=False),
        sa.Column('order_date', sa.TIMESTAMP, server_default=sa.func.now())
    )
    op.create_table(
        'OrderItems',
        sa.Column('order_item_id', sa.Integer, primary_key=True, autoincrement=True),
        sa.Column('order_id', sa.Integer, sa.ForeignKey('Orders.order_id'), nullable=False),
        sa.Column('item_id', sa.Integer, sa.ForeignKey('Items.item_id'), nullable=False),
        sa.Column('quantity', sa.Integer, nullable=False),
        sa.Column('price', sa.Float, nullable=False)
    )
    op.create_table(
        'Transactions',
        sa.Column('transaction_id', sa.Integer, primary_key=True, autoincrement=True),
        sa.Column('user_id', sa.Integer, sa.ForeignKey('Users.user_id'), nullable=False),
        sa.Column('amount', sa.Float, nullable=False),
        sa.Column('transaction_date', sa.TIMESTAMP, server_default=sa.func.now())
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Transactions')
    op.drop_table('OrderItems')
    op.drop_table('Orders')
    op.drop_table('Cart')
    op.drop_table('Items')
    op.drop_table('Users')
    # ### end Alembic commands ###
