"""Add category to Items and insert sample data

Revision ID: 741e0a2c5daf
Revises: 2feb1a462008
Create Date: 2024-06-26 22:52:10.046621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '741e0a2c5daf'
down_revision = '2feb1a462008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(), nullable=False))

    # Insert sample data
    op.execute("""
        INSERT INTO "Items" (name, description, price, stock, category) VALUES 
        ('Apple', 'Fresh red apples', 0.5, 100, 'Fruits'),
        ('Banana', 'Fresh yellow bananas', 0.3, 150, 'Fruits'),
        ('Carrot', 'Fresh orange carrots', 0.4, 200, 'Vegetables'),
        ('Broccoli', 'Fresh green broccoli', 0.8, 120, 'Vegetables'),
        ('Strawberry', 'Fresh red strawberries', 1.0, 50, 'Berries'),
        ('Blueberry', 'Fresh blueberries', 1.2, 60, 'Berries'),
        ('Chicken Breast', 'Fresh chicken breast', 3.5, 80, 'Meat'),
        ('Salmon Fillet', 'Fresh salmon fillet', 5.0, 70, 'Fish'),
        ('Milk', 'Fresh milk', 1.1, 90, 'Dairy'),
        ('Cheese', 'Fresh cheese', 2.5, 60, 'Dairy'),
        ('Yogurt', 'Fresh yogurt', 1.0, 100, 'Dairy'),
        ('Bread', 'Fresh bread', 1.5, 75, 'Bakery'),
        ('Croissant', 'Fresh croissant', 1.8, 80, 'Bakery'),
        ('Eggs', 'Fresh eggs', 2.0, 100, 'Dairy'),
        ('Tomato', 'Fresh tomatoes', 0.6, 150, 'Vegetables'),
        ('Cucumber', 'Fresh cucumbers', 0.5, 130, 'Vegetables'),
        ('Lettuce', 'Fresh lettuce', 0.7, 90, 'Vegetables'),
        ('Orange', 'Fresh oranges', 0.9, 110, 'Fruits'),
        ('Grapes', 'Fresh grapes', 2.2, 70, 'Fruits'),
        ('Avocado', 'Fresh avocados', 1.5, 60, 'Fruits');
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Items', schema=None) as batch_op:
        batch_op.drop_column('category')

    # Remove sample data
    op.execute("""
        DELETE FROM "Items" WHERE name IN (
            'Apple', 'Banana', 'Carrot', 'Broccoli', 'Strawberry', 'Blueberry', 
            'Chicken Breast', 'Salmon Fillet', 'Milk', 'Cheese', 'Yogurt', 
            'Bread', 'Croissant', 'Eggs', 'Tomato', 'Cucumber', 'Lettuce', 
            'Orange', 'Grapes', 'Avocado'
        );
    """)
    # ### end Alembic commands ###
