"""Add category and image path to Products

Revision ID: bf84e241b907
Revises: 35208eedc4fb
Create Date: 2024-06-27 10:43:39.216503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf84e241b907'
down_revision = '35208eedc4fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(), nullable=False, server_default='default_category'))
        batch_op.add_column(sa.Column('image_path', sa.String(), nullable=True))

    # Remove the server default in a separate step
    with op.batch_alter_table('Products', schema=None) as batch_op:
        batch_op.alter_column('category', server_default=None)

    # Insert sample data with image paths in smaller chunks
    op.execute("""
        INSERT INTO "Products" (name, description, price, quantity, category, image_path) VALUES 
        ('Apple', 'Fresh red apples', 0.5, 100, 'Fruits', 'assets/images/product_images/Apple.jpg'),
        ('Banana', 'Fresh yellow bananas', 0.3, 150, 'Fruits', 'assets/images/product_images/Banana.jpg'),
        ('Carrot', 'Fresh orange carrots', 0.4, 200, 'Vegetables', 'assets/images/product_images/Carrot.jpg'),
        ('Milk', 'Fresh milk', 1.1, 90, 'Dairy', 'assets/images/product_images/Rokiskio_milk.jpg'),
        ('Eggs', 'Fresh eggs', 2.0, 100, 'Dairy', 'assets/images/product_images/IKI_eggs.jpg'),
        ('Orange', 'Fresh oranges', 0.9, 110, 'Fruits', 'assets/images/product_images/Orange.jpg'),
        ('Apple Juice', 'Fresh apple juice', 2.5, 50, 'Beverages', 'assets/images/product_images/Apple_juice.jpg'),
        ('Bread', 'Fresh bread', 1.5, 75, 'Bakery', 'assets/images/product_images/Agotos_bread.jpg'),
        ('Mint Chewing Gum', 'Fresh mint chewing gum', 0.8, 200, 'Snacks', 'assets/images/product_images/Mint_chewing_gum.jpg'),
        ('Vanilla Ice Cream', 'Fresh vanilla ice cream', 3.0, 60, 'Desserts', 'assets/images/product_images/Vanilla_icecream.jpg'),
        ('Charlize Wine', 'Fresh charlize wine', 10.0, 40, 'Beverages', 'assets/images/product_images/Charlize_wine.jpg'),
        ('Chips Estrella', 'Fresh chips estrella', 1.5, 150, 'Snacks', 'assets/images/product_images/Chips_Estrella.jpg');
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Products', schema=None) as batch_op:
        batch_op.drop_column('image_path')
        batch_op.drop_column('category')

    # Remove sample data
    op.execute("""
        DELETE FROM "Products" WHERE name IN (
            'Apple', 'Banana', 'Carrot', 'Milk', 'Eggs', 'Orange', 'Apple Juice',
            'Bread', 'Mint Chewing Gum', 'Vanilla Ice Cream', 'Charlize Wine', 'Chips Estrella'
        );
    """)
    # ### end Alembic commands ###
